# Representa los datos del usaurio AAVV (Agencia de viajes)
Navicu\Core\Domain\Model\Entity\AAVVAddress:
    type: entity
    table: aavv_address
    repositoryClass: Navicu\InfrastructureBundle\Repositories\DbAAVVAddressRepository
    # Clave primaria
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        address:
            type: string
            nullable: true
        bank_account:
            type: string
            nullable: true
        email:
            type: string
            nullable: true
            length: 255
        phone:
            type: string
            nullable: true
            length: 30
        swift:
            type: string
            nullable: true
            length: 14
#       Direccion fisica valor = 0 ... direccion de facturacion valor = 2
        type_address:
            type: integer
            nullable: false
        zip_code:
            type: string
            nullable: true

#    Atributos para los logs
        createdAt:
            type: datetime
            nullable: true
        createdBy:
            type: integer
            nullable: true
        updatedAt:
            type: datetime
            nullable: true
        updatedBy:
            type: integer
            nullable: true

    manyToOne:
        aavv:
            targetEntity: Navicu\Core\Domain\Model\Entity\AAVV
            inversedBy: aavv_address
            joinColumn:
                name: aavv_id
                referencedColumnName: id
            cascade: ["persist"]
        location:
            targetEntity: Location
            inversedBy: aavv_address
            joinColumn:
                name: location_id
                referencedColumnName: id
            cascade: ["persist"]