Navicu\Core\Domain\Model\Entity\AAVVDocument:
    type: entity
    table: aavv_document
    repositoryClass: Navicu\InfrastructureBundle\Repositories\DbAAVVDocumentRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:

        type:
            type: string
            nullable: true
        createdAt:
            type: datetime
            nullable: true
        createdBy:
            type: integer
            nullable: true
        updatedAt:
            type: datetime
            nullable: true
        updatedBy:
            type: integer
            nullable: true
    manyToOne:
        aavv:
            targetEntity: Navicu\Core\Domain\Model\Entity\AAVV
            cascade: {  }
            mappedBy: null
            inversedBy: aavv
            joinColumns:
                aavv:
                    referencedColumnName: id
            orphanRemoval: false
            cascade: ["persist"]
    oneToOne:
        document:
            targetEntity: Document
            joinColumn:
                document_id:
                    referencedColumnName: id
            cascade: ["persist", "remove"]