Navicu\Core\Domain\Model\Entity\AAVVStagingAdditionalQouta:
    type: entity
    table: aavv_staging_additional_quotas
    repositoryClass: Navicu\InfrastructureBundle\Repositories\DbAAVVStagingAdditionalQoutaRepository
    # Clave primaria
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        oldamount:
            type: integer
            nullable: true
        newamount:
            type: integer
            nullable: false
#        targetid:
#            type: integer
#            nullable: false
        valid_since:
            type: date
            nullable: false
        applied:
            type: boolean
            nullable: false
            options:
              default: false

        createdAt:
            type: datetime
            nullable: true
        createdBy:
            type: integer
            nullable: true
        updatedAt:
            type: datetime
            nullable: true
        updatedBy:
            type: integer
            nullable: true

    manyToOne:
        targetid:
            targetEntity: Navicu\Core\Domain\Model\Entity\AAVVAdditionalQuota
            joinColumn:
                name: targetid
                referencedColumnName: id
            cascade: ["persist","remove"]
            nullable: false