Navicu\Core\Domain\Model\Entity\AAVVInvoice:
    type: entity
    table: aavv_invoice
    repositoryClass: Navicu\InfrastructureBundle\Repositories\DbAAVVInvoiceRepository
    # Clave primaria
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        date:
            type: date
            nullable: false
#       fecha de vencimiento
        due_date:
            type: date
            nullable: false
        description:
            type: string
            length: 255
            nullable: false
        number:
            type: string
            nullable: true
        status:
            type: integer
            nullable: true
        number:
            type: string
            nullable: true
        tax:
            type: float
            nullable: true
        tax_rate:
            type: float
            nullable: true
        subtotal:
            type: float
            nullable: true
        total_amount:
            type: float
            nullable: true
            precision: 10
            scale: 0
        type:
            type: string
            length: 100
            nullable: false

        createdAt:
            type: datetime
            nullable: true
        createdBy:
            type: integer
            nullable: true
        updatedAt:
            type: datetime
            nullable: true
        updatedBy:
            type: integer
            nullable: true

    oneToMany:
        allocation:
            targetEntity: AAVVAllocationOfInvoicePayment
            mappedBy: invoice
        aavv_reservation_group:
            targetEntity: Navicu\Core\Domain\Model\Entity\AAVVReservationGroup
            mappedBy: aavv_invoice
            cascade: ["persist"]
        lines:
            targetEntity: Navicu\Core\Domain\Model\Entity\AAVVInvoiceDetail
            mappedBy: invoice
            cascade: ["persist"]

    manyToOne:
        aavv:
            targetEntity: AAVV
            inversedBy: invoices
            joinColumn:
                name: aavv_id
                referencedColumnName: id
            cascade: ["persist"]
        currency_type:
            targetEntity: CurrencyType
            joinColumn:
                name: currency_type
                referencedColumnName: id