# Representan las agrupaciones de reservas realizadas por la AAVV (Agencia de viajes)
Navicu\Core\Domain\Model\Entity\AAVVReservationGroup:
    type: entity
    table: reservation_group
    repositoryClass: Navicu\InfrastructureBundle\Repositories\DbAAVVReservationGroupRepository
    # Clave primaria
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        public_id:
            type: string
            nullable: false
        date_check_in:
            type: date
            nullable: false
        date_check_out:
            type: date
            nullable: false
        total_amount:
            type: float
            nullable: true
        status:
            type: integer
            nullable: true
            options:
              default: 0
        hash_url:
            type: string
            nullable: true

#   Parametros para las auditorias
        createdAt:
            type: datetime
            nullable: true
        createdBy:
            type: integer
            nullable: true
        updatedAt:
            type: datetime
            nullable: true
        updatedBy:
            type: integer
            nullable: true

    oneToMany:
        reservation:
            targetEntity: Navicu\Core\Domain\Model\Entity\Reservation
            mappedBy: aavv_reservation_group
            cascade: ["persist"]
    manyToOne:
        aavv:
            targetEntity: Navicu\Core\Domain\Model\Entity\AAVV
            inversedBy: aavv_reservation_group
            joinColumn:
                name: aavv_id
                referencedColumnName: id
            cascade: ["persist"]
        aavv_invoice:
            targetEntity: Navicu\Core\Domain\Model\Entity\AAVVInvoice
            inversedBy: aavv_reservation_group
            joinColumn:
                name: aavv_invoice_id
                referencedColumnName: id
            cascade: ["persist"]
        aavv_profile:
            targetEntity: Navicu\Core\Domain\Model\Entity\AAVVProfile
            mappedBy: aavv_reservation_group
            joinColumn:
                name: aavv_profile_id
                referencedColumnName: id
            cascade: ["persist"]
        location:
            targetEntity: Navicu\Core\Domain\Model\Entity\Location
            mappedBy: aavv_reservation_group
            cascade: ["persist"]
            joinColumn:
                name: location_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [publicIdToString]
        postPersist: [generateHashUrl]
