Navicu\Core\Domain\Model\Entity\AAVVInvoiceDetail:
    type: entity
    table: aavv_invoice_details
    repositoryClass: Navicu\InfrastructureBundle\Repositories\DbAAVVInvoiceDetailRepository
    # Clave primaria
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        date:
            type: date
            nullable: false
        description:
            type: string
            nullable: false
        quantity:
            type: integer
            nullable: false
        price:
            type: float
            nullable: false
        total:
            type: float
            nullable: false
        tax_rate:
            type: float
            nullable: false

        createdAt:
            type: datetime
            nullable: true
        createdBy:
            type: integer
            nullable: true
        updatedAt:
            type: datetime
            nullable: true
        updatedBy:
            type: integer
            nullable: true

    manyToOne:
        invoice:
            targetEntity: AAVVInvoice
            inversedBy: lines
            joinColumn:
                name: invoice_id
                referencedColumnName: id
            cascade: ["persist"]