Navicu\Core\Domain\Model\Entity\Accommodation:
    type: entity
    table: accommodation
    repositoryClass: Navicu\InfrastructureBundle\Repositories\DbAccommodationRepository

    id:
        id:
          type: integer
          generator:
            strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            nullable: false
        code:
            type: string
            nullable: false
            options:
              default: ''