Navicu\Core\Domain\Model\Entity\DestinationsType:
    type: entity
    table: destinations_type
    repositoryClass: Navicu\InfrastructureBundle\Repositories\DbDestinationsTypeRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            nullable: false

    oneToMany:
        locations:
            targetEntity: Location
            mappedBy: destination_type
            cascade: ["persist"]
