Navicu\Core\Domain\Model\Entity\RoomLinkage:
    type: entity
    table: room_linkage
    repositoryClass: Navicu\InfrastructureBundle\Repositories\DbRoomLinkageRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        start_date:
            type: date
            nullable: false
        end_date:
            type: date
            nullable: false
        is_linked_availability:
            type: integer
            nullable: true
        is_linked_max_night:
            type: integer
            nullable: true
        is_linked_min_night:
            type: integer
            nullable: true
        is_linked_stop_sell:
            type: boolean
            nullable: false
        is_linked_cut_off:
            type: integer
            nullable: true

    manyToOne:
        child:
            targetEntity: Room
            cascade: {  }
            mappedBy: null
            inversedBy: i_am_child
            joinColumn:
                child_id:
                    referencedColumnName: id
            orphanRemoval: false
        parent:
            targetEntity: Room
            cascade: {  }
            mappedBy: null
            inversedBy: i_am_parent
            joinColumn:
                parent_id:
                    referencedColumnName: id
            orphanRemoval: false
