#Resetting extranet register
navicu_extranet_resetting_register:
    pattern:  /resetting
    defaults: { _controller: NavicuInfrastructureBundle:Security\Resetting:request }

navicu_extranet_resetting_register_send_email:
    pattern:  /resetting/sendEmail
    defaults: { _controller: NavicuInfrastructureBundle:Security\Resetting:sendEmail}

navicu_extranet_resetting_register_check_email:
    pattern:  /resetting/checkEmail
    defaults: { _controller: NavicuInfrastructureBundle:Security\Resetting:checkEmail}

navicu_extranet_resetting_register_reset:
    pattern:  /resetting/rest/{token}
    defaults: { _controller: NavicuInfrastructureBundle:Security\Resetting:reset}

navicu_extranet_resetting_register_update_password_success:
    pattern: /resetting/updatePasswordSuccess
    defaults: { _controller: NavicuInfrastructureBundle:Security\Resetting:passwordUpdateSuccess}