services:

#Servicios de Infraestructura
    RepositoryFactory:
        class: Navicu\InfrastructureBundle\Resources\Services\RepositoryFactory
        arguments: ["@doctrine.orm.entity_manager"]
    FormTempOwner:
        class: Navicu\InfrastructureBundle\Resources\Services\FormTempOwner
        arguments: ["@RepositoryFactory","@security.context"]
    pdfCreator:
        class: Navicu\InfrastructureBundle\Resources\Services\pdf\pdfCreator
        arguments: ["@slik_dompdf"]

    EmailService:
        class: Navicu\InfrastructureBundle\Resources\Services\EmailService
        arguments:
            - @service_container
    ManagerBDService:
        class: Navicu\InfrastructureBundle\Resources\Services\ManagerBD
        arguments:
            - @doctrine.orm.entity_manager
    CalendarService:
        class: Navicu\InfrastructureBundle\Resources\Services\CalendarService
        arguments: ["@service_container", "@translator"]


#Servicios de la Aplicación
    CommandBus:
        class: Navicu\Core\Application\Services\CommandBus
        arguments: ["@RepositoryFactory","@EmailService","@ManagerBDService"]
    RegisterTempOwner:
        class: Navicu\Core\Application\Services\RegisterTempOwner
        arguments: ["@RepositoryFactory"]
    Pagination:
        class: Navicu\InfrastructureBundle\Resources\Services\PaginationService
        arguments:
            - @service_container
    AdminProperties:
        class: Navicu\InfrastructureBundle\Resources\Services\Admin\PropertiesService
        arguments: ['@RepositoryFactory']

    SessionService:
        class: Navicu\InfrastructureBundle\Resources\Services\SessionService
        arguments:
            - @service_container
            - @security.context


    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public: false
        arguments:
            - "pgsql:host=%database_host%;dbname=%database_name%"
            - db_username: %database_user%
              db_password: %database_password%
              db_table: session
              db_id_col: session_id
              db_data_col: session_value
              db_time_col: session_time
              db_lifetime_col: session_lifetime
              lock_mode: 0 # LOCK_NONE
