imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: assets.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: false }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
      #   assets_base_urls:
      #      http:
       #         - "http://%domain%/"

    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        cookie_lifetime: 0  #time in seconds
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path: "%kernel.root_dir%/sessions"
        cookie_domain: ".%domain%"
        name: SFSESSID
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'NavicuInfrastructureBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ "NavicuInfrastructureBundle" ]
    workers:
        cache_busting:
            enabled:        true
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        mapping_types:
            json: json_array

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            string_functions:
                unaccent: Navicu\InfrastructureBundle\Resources\Services\UnaccentService
        mappings:
            NavicuDomain:
                type: yml
                prefix: Navicu\Core\Domain\Model\Entity
                dir: %kernel.root_dir%/../src/Navicu/InfrastructureBundle/Resources/config/doctrine/Domain/Entity
                is_bundle: false
            # Mapeo de Objeto Valor por medio de Doctrine/ORM 2.5 (version no estable)
#            NavicuValueObject:
#                type: yml
#                prefix: Navicu\Core\Domain\ValueObject
#                dir: %kernel.root_dir%/../src/Navicu/InfrastructureBundle/Resources/config/doctrine/Domain/ValueObject
#                is_bundle: false
#            InfrastructureDomain:
#                type: yml
#                prefix: Navicu\InfrastructureBundle\Entity
#                dir: %kernel.root_dir%/../src/Navicu/InfrastructureBundle/Resources/config/doctrine/Infrastructure
#                is_bundle: false

            NavicuInfrastructureBundle:
                type: yml
                dir: Resources/config/doctrine/Infrastructure

            NavicuRestApiBundle:
                type: yml
                dir: Resources/config/doctrine


#            InfrastructureBundle:
#               type: yml
#                dir: Resources/config/doctrine/Infrastructure

            #RestDomain:
#                type: yml
#                prefix: Navicu\Rest\ApiBundle\Entity
#               dir: %kernel.root_dir%/../src/Navicu/Rest/ApiBundle/Resources/config/doctrine
#                is_bundle: false

            gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree # this one is optional and will default to the name set for the mapping
                is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    default_mailer: first_mailer
    mailers:
        first_mailer:
            transport:  gmail
            username:   %email_account%
            password:   %email_password%
            spool:
                type: file
                path: "%kernel.root_dir%/spool"

# StofDoctrine
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true

fos_user:
# tipo de ORM/ODB que utilizas (también puede ser 'mongodb', 'couchdb' y 'propel')
    db_driver:     orm
    # el nombre de tu firewall
    firewall_name: main
    # el namespace de tu clase 'User' específica
    user_class: Navicu\InfrastructureBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        form:
            type: fosuser_registration
    resetting:
        email:
            from_email:
                address:        webmaster@navicu.com
                sender_name:    navicu_webmaster
            template: NavicuInfrastructureBundle:Resetting:email.html.twig

liip_imagine:
    resolvers:
        default:
            web_path:
              web_root: %kernel.root_dir%/../web/
              cache_prefix: uploads/images

    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web/uploads/images/images_original

    driver:               gd
    cache:                default
    data_loader:          default
    default_image:        default

    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction

    filter_sets:
        # Prototype
        images_original:
            quality:              100
            jpeg_quality:         100
            png_compression_level:  9
            png_compression_filter: ~
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        ~
            filters:
                auto_rotate: ~
                upscale: { min: [1040,800] }
                thumbnail: { size: [1040,800], mode: inset  }


        images_md:
            quality:              100
            jpeg_quality:         100
            png_compression_level:  9
            png_compression_filter: ~
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        ~
            filters:
                auto_rotate: ~
                upscale: { min: [580,420] }
                thumbnail: { size: [580,420], mode: inset  }

        images_sm:
            quality:              100
            jpeg_quality:         100
            png_compression_level:  9
            png_compression_filter: ~
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        ~
            filters:
                auto_rotate: ~
                upscale: { min: [320, 210] }
                thumbnail: { size: [320,210], mode: inset  }

        images_xs:
            quality:              100
            jpeg_quality:         100
            png_compression_level:  9
            png_compression_filter: ~
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        ~
            filters:
                auto_rotate: ~
                upscale: { min: [160, 160] }
                thumbnail: { size: [160,160], mode: inset  }

        images_email:
            quality:              100
            jpeg_quality:         100
            png_compression_level:  9
            png_compression_filter: ~
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        ~
            filters:
                auto_rotate: ~
                upscale: { min: [634, 246] }
                thumbnail: { size: [634,246],  mode: outbound  }

# Twig datetime localization
services:
    fos_user.doctrine_registry:
        alias: doctrine
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    fos_user.doctrine_registry:
        alias: doctrine

# Doctrine migrations config
doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

bazinga_js_translation:
    locale_fallback:    es
    default_domain:     messages
    active_domains:
        - messages

fos_oauth_server:
    db_driver: orm
    client_class:        Navicu\Rest\ApiBundle\Entity\OAuthClient
    access_token_class:  Navicu\Rest\ApiBundle\Entity\OAuthAccessToken
    refresh_token_class: Navicu\Rest\ApiBundle\Entity\OAuthRefreshToken
    auth_code_class:     Navicu\Rest\ApiBundle\Entity\OAuthAuthCode
    service:
        user_provider: fos_user.user_manager

nelmio_api_doc:
    name:                       'API Navicu'
    exclude_sections:           []
    default_sections_opened:    false
    sandbox:
        enabled:              false
#        endpoint:             null
#       accept_type:          null
#        body_format:
#            formats:

                # Defaults:
#                - form
#                - json
#            default_format:       ~ # One of "form"; "json"
#        request_format:
#            formats:

                # Defaults:
 #               json:                application/json
 #               xml:                 application/xml
 #           method:               ~ # One of "format_param"; "accept_header"
 #           default_format:       json
 #       authentication:
 #           delivery:             ~ # Required
 #           name:                 ~ # Required

            # Required if http delivery is selected.
#            type:                 ~ # One of "basic"; "bearer"
#            custom_endpoint:      false
#        entity_to_choice:         true
 #   routes:
 #       path_patterns: # an array of regexps
 #           - ^/api

