_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error

_main:
    resource: routing.yml

_test_email:
    pattern: /emailTest/{email}/{send}
    defaults: { _controller: NavicuInfrastructureBundle:Web\TestEmail:loadTemplate }

_test_email_campaign:
    path:   /emailCampaign/{email}/{send}
    defaults: { _controller: NavicuInfrastructureBundle:Web\TestEmail:loadCampaign }

_test_image_upload_view:
    pattern: /testUpload
    defaults: { _controller: NavicuInfrastructureBundle:AAVV\Registration:testing }

_test_image_upload:
    pattern: /testUploadImage
    defaults: { _controller: NavicuInfrastructureBundle:AAVV\Registration:uploadTesting }

_test_image_delete:
    pattern: /testDeleteImage
    defaults: { _controller: NavicuInfrastructureBundle:AAVV\Registration:deleteTesting }

_test_invoices:
    pattern: /testinvoices
    defaults: { _controller: NavicuInfrastructureBundle:AAVV/Billing:testing}

_test_seo_properties:
    path: /property_seo
    defaults: { _controller: NavicuInfrastructureBundle:Web\TestSEO:SEOProperties }

_airport_coordinates:
    path: /coordinates
    defaults: { _controller: NavicuInfrastructureBundle:Web\TestSEO:coordinates }

