Navicu\InfrastructureBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: Navicu\InfrastructureBundle\Repositories\DbUserRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
            nullable: true
        createdBy:
            type: integer
            nullable: true
        updatedAt:
            type: datetime
            nullable: true
        updatedBy:
            type: integer
            nullable: true
        disable_advance:
            type: boolean
            nullable: true


    manyToMany:
        # Conjunto de hobbies asociados al sistema
        role:
            targetEntity: Navicu\InfrastructureBundle\Entity\Role
            joinTable:
                name: user_roles
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id
            cascade: ["persist"]
    oneToOne:
        owner_profile:
            targetEntity: Navicu\Core\Domain\Model\Entity\OwnerProfile
            inversedBy: user
            joinColumn:
                owner_profile:
                    referencedColumnName: id
            cascade: ["persist"]

        aavv_profile:
            targetEntity: Navicu\Core\Domain\Model\Entity\AAVVProfile
            inversedBy: user
            cascade: ["persist"]

        temp_owner:
            targetEntity: Navicu\Core\Domain\Model\Entity\TempOwner
            inversedBy: user_id
            joinColumn:
                temp_owner:
                    referencedColumnName: id

        client_profile:
            targetEntity: Navicu\Core\Domain\Model\Entity\ClientProfile
            mappedBy: user
            cascade: ["persist"]

        commercial_profile:
            targetEntity: Navicu\Core\Domain\Model\Entity\CommercialProfile
            mappedBy: user
            cascade: ["persist"]

        reservation_change_history:
            targetEntity: Navicu\Core\Domain\Model\Entity\ReservationChangeHistory
            inversedBy: user
            referencedColumnName: id

        nvc_profile:
            targetEntity: Navicu\Core\Domain\Model\Entity\NvcProfile
            inversedBy: user
            cascade: ["persist"]


    oneToMany:
        notification_output:
            targetEntity: Navicu\Core\Domain\Model\Entity\Notification
            mappedBy: sender

        notification_input:
            targetEntity: Navicu\Core\Domain\Model\Entity\Notification
            mappedBy: reciver

        advance_deactivations:
            targetEntity: DisableAdvance
            mappedBy: user_id
            cascade: ["persist"]

        deactivations_applied:
            targetEntity: DisableAdvance
            mappedBy: deactiveBy
            cascade: ["persist"]
            
    manyToOne:
        logs_users:
            targetEntity: Navicu\Core\Domain\Model\Entity\LogsUser
            inversedBy: user
            cascade: ["persist"]

        subdomain:
            targetEntity: Navicu\InfrastructureBundle\Entity\Subdomain
            inversedBy: users
            cascade: ["persist"]